# Generated by Django 5.2.15 on 2026-06-20 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('barcode_value', models.CharField(db_index=True, max_length=128, unique=True)),
                ('barcode_type', models.CharField(choices=[('qr', 'QR Code'), ('code128', 'Code 128'), ('code39', 'Code 39'), ('ean13', 'EAN-13')], default='qr', max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=128)),
                ('model_number', models.CharField(blank=True, max_length=128)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assets/photos/')),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
