# Generated by Django 5.2.15 on 2026-06-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Asset Tracking', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Track every asset. Anywhere.', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('header_html', models.TextField(blank=True, help_text='Custom HTML for the main header area.')),
                ('footer_html', models.TextField(blank=True, help_text='Custom HTML for the footer.')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('accent_color', models.CharField(default='#8b5cf6', max_length=7)),
                ('header_bg', models.CharField(default='#0f172a', max_length=7)),
                ('footer_bg', models.CharField(default='#0f172a', max_length=7)),
                ('login_title', models.CharField(default='Welcome back', max_length=120)),
                ('login_subtitle', models.CharField(default='Sign in to manage your assets', max_length=255)),
                ('dashboard_title', models.CharField(default='Dashboard', max_length=120)),
                ('assets_page_title', models.CharField(default='Assets', max_length=120)),
                ('scan_page_title', models.CharField(default='Scan Assets', max_length=120)),
                ('status_page_title', models.CharField(default='System Status', max_length=120)),
                ('custom_css', models.TextField(blank=True, help_text='Additional CSS injected site-wide.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Branding',
                'verbose_name_plural': 'Site Branding',
            },
        ),
    ]
